### ISSUE TITLE
Suggest a tool which is using this project as a proxy

### ISSUE THREAD

**Issue by LinuxSuRen** [DaoCloud/public-binary-files-mirror#40]
We can find so many awesome tools on GitHub. I'm a maintainer of [a package installer project](https://github.com/LinuxSuRen/http-downloader). It can install those tools such as:

```shell
# install github.com/cli/cli which is the github cli
hd install cli/cli

# or you can use a shorter command
hd i cli/cli
```

user could choose the proxy via: `hd setup`. Or choose the proxy manually:

```shell
hd i cli/cli --proxy-github files.m.daocloud.io
```

I can put the usage in the readme file of this project if you belive it's ok. I really want to hear some feedback. Please left your comments below.

**Comment by wzshiming** [comment]
Sorry for the late reply. I seem to have turned off the repo notification.

Feel free, but I'm not sure if this project will add the allowlist limit in the future.

**Comment by LinuxSuRen** [comment]
> I'm not sure if this project will add the allowlist limit in the future

It is all right. No one can promise anything about the future.
