### ISSUE TITLE
不能下载rpm？

### ISSUE THREAD

**Issue by chenshanping** [DaoCloud/public-binary-files-mirror#41]
wget https://files.m.daocloud.io/github.com/Mirantis/cri-dockerd/releases/download/v0.3.1/cri-dockerd-0.3.1-3.el7.x86_64.rpm
--2024-08-24 10:44:08--  https://files.m.daocloud.io/github.com/Mirantis/cri-dockerd/releases/download/v0.3.1/cri-dockerd-0.3.1-3.el7.x86_64.rpm
Resolving files.m.daocloud.io (files.m.daocloud.io)... 47.103.132.72
Connecting to files.m.daocloud.io (files.m.daocloud.io)|47.103.132.72|:443... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2024-08-24 10:44:11--  (try: 2)  https://files.m.daocloud.io/github.com/Mirantis/cri-dockerd/releases/download/v0.3.1/cri-dockerd-0.3.1-3.el7.x86_64.rpm
Connecting to files.m.daocloud.io (files.m.daocloud.io)|47.103.132.72|:443... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2024-08-24 10:44:14--  (try: 3)  https://files.m.daocloud.io/github.com/Mirantis/cri-dockerd/releases/download/v0.3.1/cri-dockerd-0.3.1-3.el7.x86_64.rpm
Connecting to files.m.daocloud.io (files.m.daocloud.io)|47.103.132.72|:443... connected.
HTTP request sent, awaiting response... ^C

**Comment by wzshiming** [comment]
我试了下是可以下载的, 可能当时 服务器 负载比较高
