### ISSUE TITLE
files mirror is currently unavailable

### ISSUE THREAD

**Issue by ErikJiang** [DaoCloud/public-binary-files-mirror#43]
<img width="544" alt="image" src="https://github.com/user-attachments/assets/c6a1bccb-56cb-4c9b-bccc-a8d3b29b8bd4">

**Comment by ErikJiang** [comment]
If the reason for unavailability is that the disk space is full, could we consider adding a scheduled task to clean up the old cache and free up available space regularly?

**Comment by wzshiming** [comment]
It's restored. the disk is full.
