### ISSUE TITLE
Empty reply from server

### ISSUE THREAD

**Issue by mhkarimi1383** [DaoCloud/public-binary-files-mirror#45]
Hi
We are getting 
Empty reply from server error and connection resets today

**Comment by wzshiming** [comment]
The server disk space is full. and it cleaned up and restarted.

**Comment by mhkarimi1383** [comment]
@wzshiming

Adding a retention cronjob will fix that permanently

**Comment by wzshiming** [comment]
It does not uses k8s, it just uses docker-compose. In the near future, the service may move to another cloud, which will solve the problem incidentally.

**Comment by mhkarimi1383** [comment]
@wzshiming 
Just setting a nightly job that runs a simple find command to delete old files

**Comment by wzshiming** [comment]
The main file disk footprint is not caused by this service, but by other services filling up the disk and causing this service not to work.
